// entrypoints/popup/App.tsx
import { Component } from 'solid-js'
import ApplyWebsites from './ApplyWebsites'
import FeatureSwitch from './FeatureSwitch'
import HighlightKeywords from './HighlightKeywords'
import './style.css'

const App: Component = () => {
        return (
                <div class="popup">
                        <ApplyWebsites />
                        <HighlightKeywords />
                        <FeatureSwitch
                                featureName="highlight"
                                settings={{ color: 'string', size: 'number' }}
                        />
                        <FeatureSwitch featureName="stripe" />
                        <FeatureSwitch featureName="bionic" />
                        <FeatureSwitch featureName="translate" />
                        <FeatureSwitch featureName="ai" />
                </div>
        )
}

export default App

// entrypoints/popup/App.vue
<script lang="ts" setup>
import FeatureSwitch from './FeatureSwitch.vue'
import ApplyWebsites from './ApplyWebsites.vue'
// import HighlightKeywords from './HighlightKeywords.vue'
</script>

<template>
        <div class="popup">
                <!-- <HighlightKeywords /> -->
                <FeatureSwitch
                        feature-name="highlight"
                        :settings="{ color: 'string', size: 'number' }"
                />
                <ApplyWebsites />
                <FeatureSwitch feature-name="stripe" />
                <FeatureSwitch feature-name="bionic" />
                <FeatureSwitch feature-name="translate" />
        </div>
</template>

<style scoped>
.popup {
        padding: 8px;
        border-radius: 5px;
}
</style>
