// entrypoints/popup/ApplyWebsites.tsx
import { Component, createSignal, onMount } from 'solid-js'

const ApplyWebsites: Component = () => {
        const [currentUrl, setCurrentUrl] = createSignal('加载中...')

        onMount(() => {
                browser.runtime.sendMessage(
                        { action: 'getDomain' },
                        (response: { domain?: string }) => {
                                setCurrentUrl(response.domain || '无法获取域名')
                        }
                )
        })

        return <div class="current-domain">{currentUrl()}</div>
}

export default ApplyWebsites

// entrypoints/popup/ApplyWebsites.vue
<template>
        {{ currentUrl }}
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'

const currentUrl = ref('加载中...') // 初始化友好提示

onMounted(() => {
        browser.runtime.sendMessage({ action: 'getDomain' }, (response) => {
                currentUrl.value = response.domain || '无法获取域名'
        })
})
</script>
<style scoped>
.current-domain {
        font-weight: bold;
        color: #2c3e50;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
}
</style>
